app:
    mobile-ua-pattern: (?i)ipod|iphone|android|opera mini|blackberry|webos|ucweb|blazer|psp|iemobile
spring:
    thymeleaf:
        cache: false
    h2:
      console:
        enabled: true
        path: /h2
    datasource:
      url: jdbc:h2:file:~/test
      username: sa
      password:
      driver-class-name: org.h2.Driver
    jpa:
      show-sql: true
      open-in-view: true


